### ISSUE TITLE
Phyphy error says hyphy is not installed, even though it is.

### ISSUE THREAD

**Issue by ghost** [sjspielman/phyphy#11]
1. For `which hyphy`, I get the following output
- ~/Desktop/Executables/hyphy (Note: I have tried the full path instead of the ~ to see if that is the issue)

2. The full error is:
 ```
/bin/python /home/rijandhakal/Desktop/map-multifile-cds-to-protein-alignment/JSON_files/JSON_test/test_json_parse.py
Traceback (most recent call last):
  File "/home/rijandhakal/Desktop/map-multifile-cds-to-protein-alignment/JSON_files/JSON_test/test_json_parse.py", line 4, in <module>
    mybusted = phyphy.BUSTED(data="/home/rijandhakal/Desktop/map-multifile-cds-to-protein-alignment/JSON_files/JSON_test/OG0017921.pal.BUSTED.json")
  File "/home/rijandhakal/.local/lib/python3.9/site-packages/phyphy/analysis.py", line 744, in __init__
    super(BUSTED, self).__init__(**kwargs)
  File "/home/rijandhakal/.local/lib/python3.9/site-packages/phyphy/analysis.py", line 78, in __init__
    self.hyphy = HyPhy()
  File "/home/rijandhakal/.local/lib/python3.9/site-packages/phyphy/hyphy.py", line 108, in __init__
    raise AssertionError("\n[ERROR]: HyPhy executable not found. Please ensure it is properly installed, or in your provided local path.")
AssertionError: 
[ERROR]: HyPhy executable not found. Please ensure it is properly installed, or in your provided local path.
```

3. I am trying to work on BUSTED data and am just using the following script to test if Phypy is working properly:

```
import phyphy
from phyphy.extractor import Extractor

// I have tried to remove this line as well. But that only changes the error message to :  Install path does not contain a correctly built HyPhy.
myhyphy = phyphy.HyPhy(suppress_log=True,executable = '/home/rijandhakal/Desktop/Executables/hyphy',install_path ="/home/rijandhakal/Desktop/hyphy/")

mybusted = phyphy.BUSTED(data="/home/rijandhakal/Desktop/map-multifile-cds-to-protein-alignment/JSON_files/JSON_test/OG0017921.pal.BUSTED.json")

mybusted.run_analysis()

e = Extractor(mybusted)
```

Any help is appreciated.

**Comment by sjspielman** [comment]
Hi @RijanDhakal2055, 

`phyphy` is meant to provide assistance for using the `HYPHYMP` executable, but the newer `hyphy` executable may not place as nicely with this package. This is an update I need to implement to `phyphy` and will be coming in the next few months.

Your `hyphy` is probably properly installed, but you may only have the newer executable as opposed to the older `HYPHYMP` version.

Best,
Stephanie
